Client server
sergey-berezin/441_abramov pull request #6
Opened 2021-12-08 06:22 UTC by Crotokot

2021-12-08 06:58 UTC, sergey-berezin requested changes

2021-12-08 06:58 UTC, sergey-berezin commented on ClientServerUIApp/RecognitionServer/RecognitionServer/Controllers/DataStorageController.cs
> +        private Dictionary<uint, PictureProcessing> processors = new Dictionary<uint, PictureProcessing>();
Для обработки каждого запроса создаётся новый экземпляр контроллера. Поэтому поля экземпляра классы будут пустые. Логика с отменой вычислений работать не будет.

2021-12-08 06:58 UTC, sergey-berezin commented on ClientServerUIApp/RecognitionServer/RecognitionServer/Controllers/DataStorageController.cs
> +            processors[threadID].Cancel();
Тут всегда будет "Key not found"

2021-12-11 05:21 UTC, Crotokot commented on ClientServerUIApp/RecognitionServer/RecognitionServer/Controllers/DataStorageController.cs
> +        private Dictionary<uint, PictureProcessing> processors = new Dictionary<uint, PictureProcessing>();
Тогда я не понимаю, каким образом можно зафиксировать отмену операции на сервере. Можно, конечно, при отмене операции просто перестать клиентом принимать результаты, посылаемые сервером, но, думаю, это совсем не то, что нужно.

2021-12-15 06:13 UTC, merged